"""
Flowchart output. The Mermaid source is generated by the classifier; here we just
persist it to a .mmd file so it can be downloaded. Visual rendering and PNG/SVG
export happen client-side in the browser with Mermaid.js (no server-side headless
browser dependency).
"""
import os
from datetime import date

from ._common import safe_filename


def save_flowchart(mermaid_src: str, client_name: str, output_dir: str) -> str:
    os.makedirs(output_dir, exist_ok=True)
    fname = f"Flowchart_{safe_filename(client_name or 'system')}_{date.today().isoformat()}.mmd"
    out = os.path.join(output_dir, fname)
    with open(out, "w", encoding="utf-8") as f:
        f.write(mermaid_src or "flowchart TD\n  A[No diagram generated]")
    return out
